version: '3.4'

services:
  polyglot.web:
    image: ${DOCKER_REGISTRY-}polyglotweb
    container_name: Polyglot.Web
    build:
      context: .
      dockerfile: src/Polyglot.Web/Dockerfile
    depends_on:
      - polyglot-db

  polyglot-db:
    image: postgres:latest
    container_name: Polyglot.Db
    environment:
      - POSTGRES_DB=polyglot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - 5432:5432

  polyglot-idp:
    image: quay.io/keycloak/keycloak:latest
    container_name: Polyglot.Identity
    command: start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./.containers/identity:/opt/keycloak/data
      - ./.files/polyglot-realm-export.json:/opt/keycloak/data/import/realm.json
    ports:
      - 18080:8080

  polyglot-seq:
    image: datalust/seq:latest
    container_name: Polyglot.Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80

  polyglot-redis:
    image: redis:latest
    container_name: Polyglot.Redis
    restart: always
    ports:
      - '6379:6379'