version: '3.4'

services:
  eng-quest.web:
    image: ${DOCKER_REGISTRY-}eng-questweb
    container_name: EngQuest.Web
    build:
      context: .
      dockerfile: src/EngQuest.Web/Dockerfile
    depends_on:
      - eng-quest-db

  eng-quest-db:
    image: postgres:latest
    container_name: EngQuest.Db
    environment:
      - POSTGRES_DB=eng-quest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - 5432:5432

  eng-quest-idp:
    image: quay.io/keycloak/keycloak:latest
    container_name: EngQuest.Identity
    command: start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./.containers/identity:/opt/keycloak/data
      - ./.files/eng-quest-realm-export.json:/opt/keycloak/data/import/realm.json
    ports:
      - 18080:8080

  eng-quest-seq:
    image: datalust/seq:latest
    container_name: EngQuest.Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80

  eng-quest-redis:
    image: redis:latest
    container_name: EngQuest.Redis
    restart: always
    ports:
      - '6379:6379'